### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by yannadani** [chichilicious/embarrsingly-simple-zero-shot-learning#2]
Hi

Does the given code reproduces the result of the paper? I could not find any details in the documentation. 
Also, how does this code differ with the official implementation given by the authors? 
Can I use this code to run some experiments on some new datasets and report these results in a report or a paper?

**Comment by sbharadwajj** [comment]
Hi,

You can find all the answers on the updated README of the repository.
Yes, you can use it for your experiments.
